name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm -g install
    - name: Lint
      run: npm run lint
    - name: Test
      run: nyc npm qunit
